openapi: 3.0.0
info:
  version: 1.0.0
  title: Slack Web API docs
  description: nodecatd을 위한 API 문서입니다
  license:
    name: MIT
servers:
  - description: dev server
    url: 'http://localhost:4000/'
paths:
  /mypost:
    get:
      tags:
        - Post
      summary: get mypost
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    default: 200
                  payload:
                    type: array
                    items:
                      $ref: '#/components/schemas/Post'
  '/search/{hashtag}':
    get:
      tags:
        - Post
      summary: get posts contain hashtag
      parameters:
        - name: hashtag
          in: path
          required: true
          description: hashtag
          schema:
            type: string
            minimum: 1
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  payload:
                    type: array
                    items:
                      $ref: '#/components/schemas/Post'
  /myFollowers:
    get:
      tags:
        - User
      summary: get myfollowers
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  payload:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
components:
  schemas:
    Post:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
        content:
          type: string
        img:
          type: string
        createdAt:
          type: string
          format: date
        updatedAt:
          type: string
          format: date
        UserId:
          type: string
    User:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
        nick:
          type: string
        follow:
          type: object
          $ref: '#/components/schemas/Follow'
    Follow:
      type: object
      properties:
        followingId:
          type: integer
        followerId:
          type: integer
        createdAt:
          type: string
          format: date
        updatedAt:
          type: string
          format: date
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
